### ISSUE TITLE
add da strict sprint

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#1]
hi its me hause add the strict sprint so i dont get rubberbanded whenever i hit a fucking block or gapple on 2b, its in cosmos btw go paste it faster than light

**Comment by Sxmurai** [comment]
joined 2 hours ago sus

jk im planning on adding that shit dont worry its meant for 2b at some point, whenever i shell out $20 lol

im at school so ill probably like do shit when i get home, and its friday so pog

**Comment by HausemasterIssue** [comment]
> 
> 
> joined 2 hours ago sus
> 
> jk im planning on adding that shit dont worry its meant for 2b at some point, whenever i shell out $20 lol
> 
> im at school so ill probably like do shit when i get home, and its friday so pog

it's not worth spending $20 just to test shit. also yes i did get on 2b today but i had over 1000 ping, all i found out was snow ca works good on 2b (im using snow crack kek), snow strafe works 23/24 km/h on 2b, but one thing i found is that u cannot move sideways as fast as u can forwards with strafe, so that might be something thats important on 2b. momentum noslow mode for 2b2t works good. and i got kicked 3 mins later reeeeeeeeeeeeeeee also snow "nodesync" dosen't do shit i still got desynced. also, no matter what u do, (i tested multiple ca's and surrounds) if ca is on, and you turn on surround on 2b you will get desynced. so a word of advice is, make it so if u turn on surround ca toggles off, then back on again once u finish placing to stop from getting desynced mid fight. i built ur client and i will test it soon. also the ca dosen't have many strict features rn, so fix dat maybe.

**Comment by Sxmurai** [comment]
the client is 100% not ready to use i advise you 100% dont use it unless you wanna get desynced to shit lol

**Comment by Sxmurai** [comment]
fixed at  `d73fd61`
