### ISSUE TITLE
helpppp

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#2]
this isn't related to ur client and im sorry :P

make a pull request on my client so u can change the src ig. anyways i need help with a clickgui email me help or smthin pls.

**Comment by Sxmurai** [comment]
huh

**Comment by HausemasterIssue** [comment]
> 
> 
> huh

basically, for some reason when i build any new src or the src from my github, it says it can't load the client loader when it is there (Coremod ClientLoader: Unable to class load the plugin dev.zihasz.client.core.ClientLoader) also i need help with the clickgui so email me pls

**Comment by Sxmurai** [comment]
email me then lol
