### ISSUE TITLE
surround is broken

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#21]
**Please describe the issue you are facing.**
surround tries to place but the blocks get deleted instantly

**What is the expected outcome?**
it should be able to place the blocks

**Have you considered that this may be a configuration issue?**
maybe, but i tried it on strict 2bpvp, and normal 2bpvp, and same thing happened. i tweaked settings for a bit and it still can't place properly

**What is the context of which you are experiencing the bug?**
when i turn the module on it tries to place obi but when it places the obi it get's instantly deleted, i am using obi every time it tries to place, but when i place a piece of obi properly or update my inventory the obi returns.

**Comment by Sxmurai** [comment]
this should be mostly fixed, but i still need to fix airplacing / support blocks
