### ISSUE TITLE
rewrite noslow

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#22]
rewrite noslow except make it actually good pls i will help

**What would you like to suggest?**

get "inspiration :trollface:" from cosmos noslow

**How would this feature help?**

so i can chug gaps all fight like a pussy on 2b2t

**Do you have any code examples?**

go get "inspiration :trollface:" from here: https://github.com/linustouchtips/cosmos/blob/main/src/main/java/cope/cosmos/client/features/modules/movement/NoSlow.java

**Comment by Sxmurai** [comment]
the only thing that doesnt work is the sneak thing, im not going to completely skid from it
