### ISSUE TITLE
antidesync

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#25]
**What would you like to suggest?**

antidesync - prevents u from being desynced

**How would this feature help?**

reduce crystal pvp deaths on servers by 30%

**Do you have any code examples?**

brrrrrrrrrrrrrr https://github.com/oyzipfile/Zori_0.0.4/blob/master/club/novola/zori/module/combat/AntiDesync.java

**Comment by HausemasterIssue** [comment]
p.s: also it's been a while since a release came out and i feel like we should release one

**Comment by Sxmurai** [comment]
Does this module actually work? I've seen you talk about another client's antidesync but it was dog

**Comment by HausemasterIssue** [comment]
> 
> 
> Does this module actually work? I've seen you talk about another client's antidesync but it was dog

snow antidesync dosent work, but snow is obfed so idk how they did it, and if it is similar to zori's

**Comment by HausemasterIssue** [comment]
worth trying tho

**Comment by Sxmurai** [comment]
the sync method Zori is using is similar to what i already have in the AutoCrystal (https://github.com/Sxmurai/inferno/blob/5e926995ea84d3c98a293975ede16521427f2f87/src/main/java/me/sxmurai/inferno/features/modules/combat/AutoCrystal.java#L197#L232)

**Comment by HausemasterIssue** [comment]
yeah but zori anti desync is actually skidded from seppuku anti desync. and they added more shit to it like preventing block placing and breaking desync. i just say you put it in a seperate module lol.

code: https://github.com/seppukudevelopment/seppuku/blob/master/src/main/java/me/rigamortis/seppuku/impl/module/misc/NoDesyncModule.java
