### ISSUE TITLE
i am very mad [rant] 🦍 

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#38]
im too lazy to email lol, big rant incoming.

i am extremely pissed off. for like the past 4 times i've logged onto 2b2t, i've gotten kicked 5 minutes later. maybe it's because im using like 6 chinese clients that are from 2020, which half of the modules dont work or flag ncp a bunch. they are all free. you can't use 6 outdated shitty clients on 2b2t. everyone and their fucking dog just cops out and spends ther moms credit card on future and rusherhack and never gets kicked, and all their modules work great, they never flag NCP, they always work!!!!!! but because i dont have $20, I can't play my shitty, autistic, laggy, horrible block game server without getting kicked. i hate it so much. and the reason it's this way is because nobody wants to do anything for free, for the fun of it. the whole fucking reason im trying to learn java and make my own client, is so I don't have to use 6 outdated chinese clients anymore. i don't want to play a game where you need money to be good, or heck even money to not get kicked. i want to play a game where you dont need money, where all clients are free, safe, and open source, and updated! and if i paste from these clients when making my own, that dosent solve the problem! because those modules are chinese and from 2020. i need to make my own but idfk how to do that. i want to change that, I want to make a actually decent client for 2b2t, that is FREE, OPEN SOURCE, AND SAFE. no matter what it takes, i wanna do it. i dont want 0x22 and kalju sitting on their asses making a crap load of money, and treating their customers like shit. john is ok tho. i want to change the meta, i actually want to innovate, i want to compete with these clients, and actually be able to play my autistic block game server and have the same chance as everyone else, without giving in to these people. my whole motivation for making a client is my anger, and i will not stop till i make a client for 2b2t.org that is ACTUALLY GOOD!!!!!!!!!!!!! 

ok rant over now i feel better

**Comment by Sxmurai** [comment]
that's the whole point of this client, it'll eventually get there

**Comment by HausemasterIssue** [comment]
> 
> that's the whole point of this client, it'll eventually get there

also, can i get a bit of help with momentum? i just need the nametags to scale properly, could you look at my fork of momentum, just download the src, get the nametags to scale properly by distance so u can always see them, it shouldn't take long or be hard, most of the scaling code is already there lol. after it works good just make a pr on it and ill accept it pls :)

**Comment by Sxmurai** [comment]
sure ig?

**Comment by HausemasterIssue** [comment]
also momentum strafe goes up to 24 km/h on 2b2tpvp and strict 2b2tpvp, although sometimes it is buggy, might wanna take a look at it, could get some useful info about strafe :) make a pr for the nametags here btw: https://github.com/HausemasterIssue/momentum

**Comment by HausemasterIssue** [comment]
nvm i found nametags that are way more chad, don't bother, but gs and momentum strafe do go 24km/h+, but are a bit buggy, so might wanna get some inspiration from em
