### ISSUE TITLE
packetmibe

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#40]
**What would you like to suggest?**
packetmine, it is useful and godly on cc with silent swap on

**How would this feature help?**
as i said, using this on cc is extremley useful, and it is useful on most servers so u can catch ur enimies off guard. also something i wanna suggest is make it so it automatically switches back to ur pick, except its silent, so its like u can mine blocks with ur hand if u have a diamond pick lol.

**Do you have any code examples?**
phobos and gamesense have good packetmine's too look from

**Comment by Sxmurai** [comment]
done at commit https://github.com/Sxmurai/inferno/commit/d1b6ca5ae0734b0a488785f2d952695fe605a068
