### ISSUE TITLE
many issues

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#41]
**Please describe the issue you are facing.**
the rotations in the aura and in general the rotations make u look at the things ur rotating at legit instead of using packets. like they make ur screen actually move to what ur rotating on, we dont want that. also i couldn't get the ca to work.

**What is the expected outcome?**
the rotations should move your head, but not actually rotate to what the user is looking at on their screen

**Have you considered that this may be a configuration issue?**
ca is a config issue, or maybe its just chinese? (probably, like it didnt work at all, it didnt place break, nothing)

**What is the context of which you are experiencing the bug?**
everywhere, and in ur moms house 😎

**Comment by HausemasterIssue** [comment]
p.s. check yo email :)

**Comment by Sxmurai** [comment]
this will end up being fixed if i end up reproducing it, i cannot reproduce this bug for myself.
