### ISSUE TITLE
build issu

### ISSUE THREAD

**Issue by master7720** [Sxmurai/inferno#44]
FAILURE: Build failed with an exception.

* What went wrong:
Unable to get mutable Windows environment variable map
idk what happen

**Comment by HausemasterIssue** [comment]
look up how to build minecraft hack clients: https://www.youtube.com/watch?v=5dEgxdLUQoI and actually use google for once :)

**Comment by Sxmurai** [comment]
not a bug, changed label

**Comment by Sxmurai** [comment]
plus a quick google search should answer this:
https://stackoverflow.com/questions/67098755/build-failed-unable-to-get-mutable-windows-environment-variables

you just need to add JAVA_HOME

to be clear, i also dont reccomend using it as a main client because its still a bit buggy (rotations mostly)

**Comment by master7720** [comment]
ah ok thanks

**Comment by HausemasterIssue** [comment]
@Sxmurai close this
