### ISSUE TITLE
gapple sword offhand

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#45]
**What would you like to suggest?**
make kill aura pause for a sec when forcing a gapple in ur offhand, then resume, then when switiching back to ur totem or whatever pause kill aura for a sec until u have a totem or whatever in ur offhand, then resume kill aura if that makes sense, basically, just make kill aura pause for a sec when switching to and from a gapple in ur offhand

**How would this feature help?**
prevent u getting stuck between swapping totems and gapples causing u to get kicked or die, it also allows u to swap between gaps and totems without getting stuck

**Do you have any code examples?**
it's not that hard only hard part is calling the module lol that i wanna learn how to do

**Comment by Sxmurai** [comment]
Putting this here to remind myself:

- "Strict" mode offhand, will stop any actions (eating, attacking, etc) to swap your offhand.

Also, please fix the InventoryMove Bypass Gavin, would be nice to have

**Comment by Sxmurai** [comment]
https://github.com/Sxmurai/inferno/commit/8f5595b220f0619b82037f71babd29802a90a4c8 done in this commit
