### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by master7720** [Sxmurai/inferno#47]
Does this client have a discord?

**Comment by Sxmurai** [comment]
i almost forgot about it tbh, yeah i should probably make one. sadly hauseissue doesnt use discord so he cant even join it.

when i make it, ill respond with the invite and put it into my readme

**Comment by HausemasterIssue** [comment]
sxmurai just set up an email or i can set up an email where people send us questions lol. something like support@aestheticall.xyz or something like that idk.

**Comment by master7720** [comment]
ah ok

**Comment by Sxmurai** [comment]
thats way too much work @HausemasterIssue, discord would be easier.

**Comment by HausemasterIssue** [comment]
well yeah, but you gotta set up a whole server, and considering its agiasnt tos, if some retard decides to report it you just lost like 1 hour of work lol and you gotta get loads of ppl to join ur new server. and if you make it shitty and simple to be able to set it up again if it gets termed, people won't like it. so, yeah, idk. you decide.

**Comment by Sxmurai** [comment]
it took me barely 5 minutes to setup, it'll be fine Hause

**Comment by HausemasterIssue** [comment]
ok

**Comment by Sxmurai** [comment]
i highkey forgot about this, here's the link: https://discord.gg/J9jxrW7xeZ
