### ISSUE TITLE
speed/packet mine crashes game

### ISSUE THREAD

**Issue by HausemasterIssue** [Sxmurai/inferno#49]
**Please describe the issue you are facing.**
when i turn on speed/packet mine the game instantly crashes no questions asked

**What is the expected outcome?**
it should not crash the game when toggled on and actually work like this: https://www.youtube.com/watch?v=mrSnTDiTjj4

**Have you considered that this may be a configuration issue?**
its not a config issue

**What is the context of which you are experiencing the bug?**
when i toggle on the module

**Comment by Sxmurai** [comment]
I hadn't pushed my changes yet I don't think. I'll close it when I get back
to my PC

**Comment by HausemasterIssue** [comment]
💀
